global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "spring-actuator"
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
    - targets: ["localhost:8080"]

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets: ["localhost:9093"]

